POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "How to keep your room messy",
    "author": "Jessica Hayes",
    "url": "https://fakeassurl2.com",
    "likes": 50
}